export default {
    login: "douglasliman",
    id: 98565751,
    node_id: "U_kgDOBd_-dw",
    avatar_url: "https://avatars.githubusercontent.com/u/98565751?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/douglasliman",
    html_url: "https://github.com/douglasliman",
    followers_url: "https://api.github.com/users/douglasliman/followers",
    following_url: "https://api.github.com/users/douglasliman/following{/other_user}",
    gists_url: "https://api.github.com/users/douglasliman/gists{/gist_id}",
    starred_url: "https://api.github.com/users/douglasliman/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/douglasliman/subscriptions",
    organizations_url: "https://api.github.com/users/douglasliman/orgs",
    repos_url: "https://api.github.com/users/douglasliman/repos",
    events_url: "https://api.github.com/users/douglasliman/events{/privacy}",
    received_events_url: "https://api.github.com/users/douglasliman/received_events",
    type: "User",
    site_admin: false,
    name: "Douglas Queiroz",
    company: null,
    blog: "https://www.linkedin.com/in/douglas-queiroz",
    location: "127.0.0.1",
    email: null,
    hireable: null,
    bio: "Full-Stack Developer | Java & React\r\nLove building cool web apps with Java on the back-end and React on the front. Always learning and exploring new tech to k",
    twitter_username: null,
    public_repos: 41,
    public_gists: 0,
    followers: 25,
    following: 18,
    created_at: "2022-01-28T00:55:16Z",
    updated_at: "2024-05-27T17:19:32Z"
  
};
