export default {
  login: "douglasliman",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars.githubusercontent.com/u/98565751?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/douglasliman",
  html_url: "https://github.com/douglasliman",
  followers_url: "https://api.github.com/users/douglasliman/followers",
  following_url:
    "https://api.github.com/users/douglasliman/following{/other_user}",
  gists_url: "https://api.github.com/users/douglasliman/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/douglasliman/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/douglasliman/subscriptions",
  organizations_url: "https://api.github.com/users/douglasliman/orgs",
  repos_url: "https://api.github.com/users/douglasliman/repos",
  events_url: "https://api.github.com/users/douglasliman/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/douglasliman/received_events",
  type: "User",
  site_admin: false,
  name: "Douglas Liman",
  company: "Fullstack java react",
  blog: "douglas lima ",
  location: "Campinas",
  email: null,
  hireable: null,
  bio: "Fullstack java react",
  twitter_username: "",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
